---
title: Tidyr
author: Daniel Kim
output:
  github_document:
    toc: true
    toc_depth: 2
    fig_width: 5
    fig_height: 5
---

# Tidyr

### Objectives

## Introduction
The main use of the package tidyr is to help create **tidy data**. Tidy data is defined as:
1. Each variable is in a column.
2. Each observation is a row.
3. Each value is a cell.

You can find the official R guideline [here](https://cran.r-project.org/web/packages/tidyr/tidyr.pdf).

## Installation

The easiest way to get tidyr is to install the whole tidyverse.
Tidyverse package includes packages such as:
 - ggplot2
 - tibble
 - tidyr
 - readr
 - purrr
 - dplyr
 
You can install this packages by typing:
```
install.packages("tidyverse")
```

Alternatively, install just tidyr:
```
install.packages("tidyr")
```

Or the the development version from GitHub:
```
install.packages("devtools")
devtools::install_github("tidyverse/tidyr")
```

## Getting Started

Start by loading and attaching the package.
```
library(tidyr)
```

There are two fundamental functions used for data tidying:

- `gather()`. Takes multiple columns, and gathers them into key-value pairs: it makes “wide” data longer.
- `spread()`. Takes two columns (key & value) and spreads in to multiple columns, it makes “long” data wider.

### 1. gather()

#### Usage
```
gather(data, key, value, ..., na.rm = FALSE, convert = FALSE, factor_key = FALSE)
```
#### Arguments
Arguments  | Definition
------------- | -------------
data  | A data frame.
key, value  | Names of key and value columns to create in output.
... | Specification of columns to gather. Use bare variable names. Select all variables between x and z with x:z, exclude y with -y.
na.rm | If TRUE, will remove rows from output where the value column in NA.
convert | If TRUE will automatically run type.convert on the key column. This is useful if the column names are actually numeric, integer, or logical.
factor_key | If FALSE, the default, the key values will be stored as a character vector. If TRUE, will be stored as a factor, which preserves the original ordering of the columns.

#### Example
First lets build a "wide" data frame by typing the R code below:
````
mini_iris <- iris[c(1, 51, 101), ]
````

A visual representation of this data frame would look like this:

Sepal.Length  | Sepal.Width | Petal.Length | Petal.Width | Species
--- | --- | --- | --- | ---
1       |     5.1     |    3.5     |     1.4    |     0.2  |   setosa
51       |    7.0     |    3.2     |     4.7    |     1.4 |versicolor
101       |   6.3     |    3.3     |     6.0     |    2.5 | virginica

To have a visual representation of your data frame on your R program you can simply type:
````
View(name_of_data_frame)
````
In our example it would be:
````
View(mini_iris)
````
Now we would like to convert this "wide" data frame to a "long" data frame as shown below:

Species  | flower_att | measurement
--- | --- | ---
setosa |Sepal.Length      |   5.1
versicolor |Sepal.Length   |      7.0
virginica |Sepal.Length    |     6.3
setosa | Sepal.Width      |   3.5
versicolor | Sepal.Width   |      3.2
virginica  |Sepal.Width    |     3.3
setosa |Petal.Length     |    1.4
versicolor |Petal.Length    |     4.7
virginica |Petal.Length    |     6.0
setosa |Petal.Width    |     0.2
versicolor | Petal.Width   |      1.4
virginica | Petal.Width    |     2.5

To obtain a "long" data frame we can use the function gather() as such:
````
gather(mini_iris, key = flower_att, value = measurement, Sepal.Length, Sepal.Width, Petal.Length, Petal.Width)
````

You can obtain the same result with a less verbose solution as such:
````
gather(mini_iris, key = flower_att, value = measurement, -Species)
````

### 2. spread()

#### Usage
````
spread(data, key, value, fill = NA, convert = FALSE, drop = TRUE, sep = NULL)
````

#### Arguments
Arguments  | Definition
------------- | -------------
data | A data frame.
key | The bare (unquoted) name of the column whose values will be used as column headings.
value | The bare (unquoted) name of the column whose values will populate the cells.
fill | If set, missing values will be replaced with this value. Note that there are two types of missingness in the input: explicit missing values (i.e. NA), and implicit missings, rows that simply aren’t present. Both types of missing value will be replaced by fill.
convert | If TRUE, type.convert with asis = TRUE will be run on each of the newcolumns. This is useful if the value column was a mix of variables that was coerced to a string. If the class of the value column was factor or date, note that will not be true of the new columns that are produced, which are coerced to character before type conversion.
drop | If FALSE, will keep factor levels that don’t appear in the data, filling in missing combinations with fill.
sep | If NULL, the column names will be taken from the values of key variable. If nonNULL,the column names will be given by "<key_name><sep><key_value>".

#### Example
Spread and gather functions are complements. While gather is trying to make "wide" data frames longer, spread makes "long" data frames wider.

Lets
````
# Use 'convert = TRUE' to produce variables of mixed type
df <- data.frame(row = rep(c(1, 51), each = 3),
var = c("Sepal.Length", "Species", "Species_num"),
value = c(5.1, "setosa", 1, 7.0, "versicolor", 2))
df %>% spread(var, value) %>% str
df %>% spread(var, value, convert = TRUE) %>% str
````
