---
title: "Daily Report in RMarkdown"
author: "Albert"
output:
  github_document:
    toc: true
    toc_depth: 2
    fig_width: 5
    fig_height: 5
---

## What is the daily report
The daily report in RMarkdown will be the progress report that you send to your employer every day. This allows you to get valuable feedback and to get guidance on your progress through your data science journey. One of the most important parts of your daily report should be that you are as accurate as possible about your progress. As long as you meet your deadlines, your employer will care much more about looking through your progress and answering your questions as efficiently as possible. Fluff and extranenous information on materials you had to read in order to solve problems are better left off of your daily report.

## The format
 
 The format of the daily report should be tailored based on your needs and your employers needs. This is merely a template for what you can use as your daily report. 
 
 ```
 # Daily report for ___insert today's date___
 Name
 
 Reviewed by ____space for employer signature____
 ---------------------------------------------
 
 Tasks for today:
 - [ ] Task 1
    - [ ] Subtask 1
    - [ ] Subtask 2
    - [ ] Subtask 3
 - [ ] Task 2
    - [ ] Subtask 1
    - [ ] Subtask 2
    - [ ] Subtask 3
 - [ ] Task 3
    - [ ] Subtask 1
    - [ ] Subtask 2
    - [ ] Subtask 3
 
 -------------------------
 
 Proposed tasks for tomorrow:
 - [ ] Task 1
    - [ ] Subtask 1
    - [ ] Subtask 2
    - [ ] Subtask 3
 - [ ] Task 2
    - [ ] Subtask 1
    - [ ] Subtask 2
    - [ ] Subtask 3
 - [ ] Task 3
    - [ ] Subtask 1
    - [ ] Subtask 2
    - [ ] Subtask 3
 
 -------------------------
 
 ## Important questions or comments
 ___insert questions and comments here___
 ```
 
 When compiled the report will look something like this:
 
  # Daily report for ___insert today's date___
 Name
 
 Reviewed by ____space for employer signature____
 ---------------------------------------------
 
 Tasks for today:
 - [ ] Task 1
    - [ ] Subtask 1
    - [ ] Subtask 2
    - [ ] Subtask 3
 - [ ] Task 2
    - [ ] Subtask 1
    - [ ] Subtask 2
    - [ ] Subtask 3
 - [ ] Task 3
    - [ ] Subtask 1
    - [ ] Subtask 2
    - [ ] Subtask 3
 
 -------------------------
 
 ## Important questions or comments
 ___insert questions and comments here___
