---
title: "Xml2"
author: "Walter"
output:
  github_document:
    toc: true
    toc_depth: 2
    fig_width: 5
    fig_height: 5
---
example of use
why package important
2-3 most important functions
  reading
  display
  analysis


## xml2

The xml2 package lets you read and write html and xml documents.

## What do you mean?

An HTML document is a file that contains hypertext markup language.  In simpler terms, it means text (and images and rich text elements) that is meant to be displayed on a webpage.  You may have noticed that a number of website url's end in ".html," those pages use this hypertext markup language.

A XML document, or Extensive Markup Language, is essentially a system of formatting that creates documents that both man and machine can read.  It has a number of uses, but the one we will be focusing on is it's use in representing arbitrary data structures.

## Installation

xml2, like a number of other packages, can be installed from CRAN.

*Step 1:* Open up RStudio
*Step 2:* Type in the following *exactly* as it appears:
install.packages("xml2")
xml2 will then be installed onto your device.

## Using xml2

read_xml() and read_html()
Both of these functions, as their names suggest read whatever document is named in the argument (what is placed within the parentheses.  Here are some examples:

read_xml("<Hello>world /></Hello>")
will output:
(xml_document)
<Hello>
  
 You can even use this function to read documents by url:
 
 read_xml("http://www.xmlfiles.com/examples/cd_catalog.xml")
 or
 read_html("http://had.co.nz")
 
 Note that you must use a particular function for a particular website format.
 
 These two functions will enable a data scientist to read an xml or html file.
 
The next group of functions allow you to navigate around the family tree
xml_children returns only elements.
xml_contents returns all nodes.
xml_length returns the number of children.
xml_parent returns the parent node.
xml_parents returns all parents up to the root
xml_siblings returns all nodes at the same level


xml2 has some further uses that will not be covered in this tutorial.  If you would like to explore further, check out the documentation.  It will be on xml2's Cran page at https://cran.r-project.org/web/packages/xml2/index.html
